# Generated by Django 4.2.7 on 2023-11-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_post_create_date_post_discription_post_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meet_date',
            field=models.CharField(max_length=200),
        ),
    ]
