# Generated by Django 4.2.7 on 2023-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_post_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='promotion/'),
        ),
    ]
